output: cli
quiet: true
directory: .
download-external-modules: true
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
soft-fail: false
skip-check:
  - CKV_SECRET_6
