name: "Disable all pull requests"
env:
  module_path: "backend-tfe"
permissions:
  issues: write
  pull-requests: write

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          skip-closed-issue-comment: true
          skip-closed-pr-comment: true
          issue-comment: |
            This repo is a mirror and does not accept issues.
            Please use https://github.com/Olivr/oStack/issues instead.
          pr-comment: |
            This repo is a mirror and does not accept pull requests.
            Please use https://github.com/Olivr/oStack/tree/main/modules/${{ env.module_path }} instead.
